### ISSUE TITLE
Reddit Discussion

### ISSUE THREAD

**Issue by apearson** [andrewpe/goodlock-color-picker#7]
No luck on my Mac so far; will try Windows after a meeting.

First, tried without ADB in my $PATH:

```
❯ python hex2goodlock.py '#253f3f'
Input Hex: #253f3f
Hue Screen Location: 924.0px
Saturation Screen Location: 249.0px
Value Screen Location: 1390.0px
./mac-tools/adb shell input tap 850 924.0 && adb shell input tap 249.0 1390.0
sh: adb: command not found

❯ which adb
adb not found
```

No dice there. With ADB installed:

```
❯ brew install android-platform-tools

❯ which adb
/usr/local/bin/adb

❯ adb devices
List of devices attached
24923391    device

❯ python hex2goodlock.py '#253f3f'
Input Hex: #253f3f
Hue Screen Location: 924.0px
Saturation Screen Location: 249.0px
Value Screen Location: 1390.0px
adb shell input tap 850 924.0 && adb shell input tap 249.0 1390.0
```

USB debugging was for-sure enabled, GoodLock was on the color selector with the 4 hexagons. `brew install android-platform-tools` is a nice way for Mac users to get their `adb` and `fastboot`, if they already have `homebrew` installed... but if they do, they probably don't need much walkthrough anyways.

I'll keep you posted!

**Comment by apearson** [comment]
...and on Windows:

> `python -V`
> 
> Python 3.5.2
> 
> `which adb`
> 
> /cygdrive/c/Windows/adb
> 
> `python hex2goodlock.py '#253f3f'`
> 
> Input Hex: '#253f3f'
> 
> Traceback (most recent call last):
> 
> File "hex2goodlock.py", line 22, in <module>
> 
> rgb = int(inputHex[1:3],16), int(inputHex[3:5], 16), int(inputHex[5:7], 16))
> 
> ValueError: invalid literal for int() with base 16: '#2'

Changing the command to `python hex2goodlock.py "#253f3f"` on Windows 10 stopped the `int()` error.

I _was_ able to see the color in the Base Color scroll! However, it didn't select the correct color for the hex code, and an arbitrary hex code (#14cedb) didn't result in any scroll whatsoever. Both the color codes #253f3f and #253237 would scroll the base color over by 1 hexagon to the left for me.

**Comment by apearson** [comment]
@blindingstars

**Comment by apearson** [comment]
@blindingstars Are you using condensed mode or standard display mode

**Comment by stephymiehle** [comment]
Standard display mode, AT&T S7

**Comment by apearson** [comment]
Alright, the screen locations are different on the standard display mode.  I'm working on getting the coordinates now.

**Comment by apearson** [comment]
@blindingstars Standard display mode should be working now.  Let me know how it works for you.

**Comment by stephymiehle** [comment]
@andrewpe Still no luck on Windows:

![Screen recording](http://i.imgur.com/qRiY4Lx.gif)

Always goes one hex to the left (using one of your provided colors) or doesn't move at all (using `#14cedb` as an example). Perhaps it has to do with the starting color? Mine is a very dark charcoal grey; was yours something more colorful?

**Comment by apearson** [comment]
Off topic but how did you make that video?  That's pretty neat

I see the problem, I have the latest update that contains the custom color picker.
![screenshot_20161004-231943](https://cloud.githubusercontent.com/assets/5739091/19130843/9f3a3372-8b12-11e6-8187-66dd34f5d176.png)

**Comment by stephymiehle** [comment]
Ah! That might do it; thought my Good Lock was up to date. I feel awfully silly now; I'll go update that and give this another go.

I used [Rec](https://play.google.com/store/apps/details?id=com.spectrl.rec) to record and converted to a GIF at [ezgif](http://ezgif.com/video-to-gif/).

**Comment by stephymiehle** [comment]
Aaaand working! 💥  Safe to close here.

Since I've got everything set up, want me to make a recording of the process so that others have a visual? I'd definitely mention that Good Lock should have the Custom option and perhaps even have a screenshot there, if no video.

**Comment by apearson** [comment]
Awesome! Want me to add you to the ReadMe's beta testers and to the contributors file? 

If you don't mind doing that, it would make showing everyone else much much easier!

**Comment by stephymiehle** [comment]
Sure, and no trouble at all! Let me just decide on my colors and I'll get that recording added.

**Comment by stephymiehle** [comment]
Noticing a slight shift here:

![image](https://cloud.githubusercontent.com/assets/6765732/19131313/9a237d4c-8b14-11e6-8b37-f6267f76bef4.png)

Should be #000000, but shows up as #070707

---

![image](https://cloud.githubusercontent.com/assets/6765732/19131360/bd3eac8e-8b14-11e6-82f3-a50e220f093c.png)

Should be #464646, but shows up as #44423d

I'll still record away, as the process is the same, but maybe slight misalignment on Standard display mode?

**Comment by apearson** [comment]
You might be right, I'm going to open another issue for this.
